server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/diploma-pLMS
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true


  flyway:
    locations: classpath:db/migration

