server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/diploma-pLMS
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  flyway:
    locations: classpath:db/migration

